Update selectUserCurrentPositions to Apollo
Component-fi/perpetual-lp-tool pull request #274
Opened 2022-10-26 18:24 UTC by nickwang14

# Description
Converting fetch to use apollo

## Sanity Check
Positions are still fetched
App doesnt crash when connecting or disconnecting from wallet

## notes

2022-10-26 18:24 UTC, nickwang14 commented on src/queries/getAllPerpMarketsQuery.ts
> +export const getAllPerpMarketsQuery = gql`
Rename as we move towards Apollo fetch as standard

2022-10-27 00:32 UTC, closed without merging

2022-10-27 00:33 UTC, mattiaslightstone requested changes
It seems as though 3s has not been sufficient for the subgraph to have updated.

2022-10-27 00:33 UTC, mattiaslightstone commented on src/components/Modals/AddLiquidity/ConfirmAddLiquidity.tsx
> +// useRecoilRefresher_UNSTABLE
?

2022-10-27 00:33 UTC, mattiaslightstone commented on src/components/Modals/AddLiquidity/ConfirmAddLiquidity.tsx
> +    const resetUserCurrenPositions = useRecoilRefresher_UNSTABLE(
this is cool