Feat/current positions modal scaffold
Component-fi/perpetual-lp-tool pull request #300
Opened 2023-01-17 17:46 UTC by aindriumorris

# Description

## Sanity Check

## notes

2023-01-17 19:28 UTC, Brendan-Lucas commented on src/components/Modals/CurrentPositions/CurrentPositionsModal.module.scss
> +        .assetLogo {
This could probably be reused from somewhere else.

2023-01-17 19:28 UTC, Brendan-Lucas commented on src/components/Modals/CurrentPositions/CurrentPositionsModal.module.scss
> +        .assetText {
This also could probably be reused from other locations. maybe in our add liquidity modal.

2023-01-17 19:30 UTC, Brendan-Lucas commented on src/components/Modals/CurrentPositions/CurrentPositionsModal.module.scss
> +    .profitAndLossPositiveNegative {
Some of these styles are really redundant, I don't want to have to add all these styles for each new column added.

2023-01-17 19:32 UTC, Brendan-Lucas commented on src/components/Modals/CurrentPositions/CurrentPositionsModal.module.scss
> +        width: 183.8px;
look into child formatting or * > you can see an example of this in our metrics module which is another table. we format for each of the children of the table so that the font families and align items and whatnot are the same.

2023-01-17 19:35 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +    const historyStatus: boolean =
rename to current positions everywhere we'rare calling this history

2023-01-17 19:36 UTC, Brendan-Lucas commented on src/recoil/atoms/atoms.ts
> +export const historyButtonStatusAtom = atom({
what is history button status?

2023-01-17 19:36 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +    const historyStatus: boolean =
what is history button status

2023-01-17 19:37 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {historyStatus === false
I have learned what history button status is from context, I don't think this should be a recoil value if we are just using it in this file.

2023-01-17 19:55 UTC, Brendan-Lucas commented
Look into why its failing builds on vercel. try running a typescript compile locally to make sure everything checks out.

2023-01-17 19:56 UTC, Brendan-Lucas commented
add a description and screen shots!

2023-01-18 16:23 UTC, aindriumorris commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {historyStatus === false
We use history button status (re-named currentPositionsButtonStatus) in both the SideBarModule and the UI.
- We use the button in the sideBarModule to trigger the setCurrentPositionsButtonStatus state, which is then used to conditionally render the modal in the UI.

2023-01-18 17:02 UTC, aindriumorris commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {historyStatus === false
history button status renamed currentPositionsModalToggleStatus

2023-01-23 15:50 UTC, Brendan-Lucas requested changes

2023-01-23 15:50 UTC, Brendan-Lucas commented on src/containers/MetricsModule/MetricsModule.module.scss
> -  display: flex;
I am wonderring if this might be an error, the metrics module probably shouldn't have lost lines since it is unrelated code.

2023-01-23 15:50 UTC, Brendan-Lucas commented on src/containers/MetricsModule/MetricsModule.module.scss
>  @import '../../css/global.scss';
I am thinking that based on the contents and purpose of this PR that this file should probably be unchanged. Can you explain what's happening here?

2023-01-23 15:50 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.module.scss
> +.history:hover {
I actually dont think this should be a blue on hover, I think it should have the same behaviour as the rewards button in terms of styling. 

Also should probably be called CurrentPositions since that's what it's doing

2023-01-23 15:50 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {currentPositionsStatus === false
current positions is a boolean, you dont need to check that its false like this. if you think that it is more readable to show the negative case first, you should use !currentPositionsStatus. otherwise just currentPositions ? positive case : negative case

2023-01-23 18:15 UTC, aindriumorris commented on src/containers/SideBarModule/SideBarModule.module.scss
> +.history:hover {
Rewards button is blue on hover however?

2023-01-23 18:16 UTC, aindriumorris commented on src/containers/MetricsModule/MetricsModule.module.scss
> -  display: flex;
error

2023-01-24 19:12 UTC, Brendan-Lucas requested changes

2023-01-24 19:12 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +                        : null}
I didn't see this before but You don't need a ternary statement here. 

should be currentPositionsStatus && or !currentPositionsStatus && 

basically its a ternary without a negative option.

2023-01-24 19:12 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {!currentPositionsStatus
uppon reviewing this again I dont think this is right: 

this indicates show this current positions button if the currentPositionsStatus is false, shouldn't we only show it if currentPositionsStatus is true? 

I think this line should be replaced with:
```
{ currentPositionsStatus && ( ...
```

2023-01-24 20:32 UTC, Brendan-Lucas approved these changes

2023-01-24 20:38 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +        useRecoilValue(selectUserCurrentPositions).length > 0
this is absolutely the way we are going to check this in the future, However, on this feature branch we probably want it to just check our mocDataAtom this way we will always see it when we're trying to do things. I am thinking we comment this out and add a new variable with the same name that checks mocDataAtom.length

2023-01-25 12:22 UTC, merged