Feat/current positions modal table sort
Component-fi/perpetual-lp-tool pull request #304
Opened 2023-01-26 17:36 UTC by aindriumorris

# Description

## Sanity Check

## notes

2023-01-30 22:33 UTC, Brendan-Lucas requested changes

2023-01-30 22:33 UTC, Brendan-Lucas commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                                    {position.netPosition
why did we make this change? just wondering what we get from toLocaleString() ?

2023-01-30 22:33 UTC, Brendan-Lucas commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                            ${position.perpRewardsTotal.toLocaleString('en-US')}
same question as above & why is the "$" sign there?

2023-01-30 22:33 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +    /*
we let as few comment blocks as possible into the feature branch! we'll have to take this out before we put this in. if its necessary we can fix and implement it as code

2023-01-30 22:33 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> -                    {currentPositionsStatus && (
why did you remove this check, I think it should still be relevant and valid.

2023-01-30 22:33 UTC, Brendan-Lucas commented on src/recoil/atoms/atoms.ts
> -            netPosition: '1235.21',
im guessing that you had a type issue and had to remove the quotes?

2023-01-30 22:33 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionInformation.ts
> +    key: 'currentPositionInformation',
if you look at the rest of those keys they are in Pascal case

2023-01-31 00:06 UTC, Brendan-Lucas approved these changes

2023-01-31 00:06 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformationSorted.ts
> +        const selectedSortOption: any = sortOptions.filter((option: any) => {
we usually avoid "any" typing things, since you made the object we probably have the type info for the options

2023-01-31 00:06 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformationSorted.ts
> +        const sortStringAZ = () => {
we should probably move our sort into a utility.

2023-01-31 00:06 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformationSorted.ts
> +        const sortStringZA = () => {
same as the comment above.

2023-01-31 00:06 UTC, Brendan-Lucas requested changes
previously approved by accident, deffinately RC

2023-01-31 17:21 UTC, aindriumorris commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                                    {position.netPosition
I changed some of the atom types from strings to integers as I now know this will most match the types of the real data.
The real data won't have a $ so we include that here.
The toLocaleString simply adds commas to the integers as per the figma styling.

2023-01-31 17:22 UTC, aindriumorris commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                            ${position.perpRewardsTotal.toLocaleString('en-US')}
perpRewardsTotal is the same as above, $ won't be pulled from the data, perhaps this could be done in the selector instead?

2023-01-31 17:31 UTC, aindriumorris commented on src/recoil/atoms/atoms.ts
> -            netPosition: '1235.21',
I converted from strings to integers as this matches what real data will be, so I wanted to be adapted to that in terms of styling

2023-02-02 16:29 UTC, Brendan-Lucas requested changes

2023-02-02 16:29 UTC, Brendan-Lucas commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                            ${position.perpRewardsTotal.toLocaleString('en-US')}
oh! I thought this was a template string gone wrong! thank you for clarifying! might we make use of our "formatCurrency" utility here? let me know if it makes more sense.

2023-02-02 16:29 UTC, Brendan-Lucas commented on src/constants/enums.ts
> +export enum SortDirection {
now this makes sense here, however it might make more sense to have this be a local enum in the other file if we are only using it in one place.

2023-02-02 16:29 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {!currentPositionsStatus && (
I am seeing that you have an not operator in front but I think that this not operator should not be here. We want to see this button if a user DOES have current positions, from my understanding this will show our button only if a user DOES NOT have current positions.

2023-02-02 16:29 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformationSorted.ts
> +        const sortStringAZ = () => {
I am also noticing we might be reinventing the weel with this sort function, did you look at https://lodash.com/docs/4.17.15#orderBy
might save us some code that we don't need to maintain and test.

2023-02-02 16:29 UTC, Brendan-Lucas commented on src/utilities/sortArrayByString.ts
> +export const sortStringAZ = (array: [], property: string) => {
good move to liquidity but I think the functions are still defined in the files above as well.

2023-02-02 16:29 UTC, Brendan-Lucas commented on yarn.lock
>  "@uniswap/v3-core@1.0.0", "@uniswap/v3-core@https://github.com/Uniswap/uniswap-v3-core/tarball/v1.0.0":
now that you have cleared your package.json file we should try deleting this and pulling down the old lock file and running yarn, I think these changes should go away for the most part.

2023-02-02 16:54 UTC, aindriumorris commented on src/containers/SideBarModule/SideBarModule.tsx
> +                    {!currentPositionsStatus && (
yes you are correct, I had it in this way to make the modal render locally without needing to open a wallet, I'll make the correction

2023-02-02 17:19 UTC, aindriumorris commented on src/recoil/selectors/selectCurrentPositionsInformationSorted.ts
> +        const sortStringAZ = () => {
I think declaring the sort outside of the sortedTableData function where it is called, aids in readability as opposed to sortedTableData having nested conditions and then detailed sort function return calls aswell.
I will change the sortStringAZ/ZA to use orderBy

2023-02-03 17:09 UTC, Brendan-Lucas commented
> ## Screenshot
> ![2023-01-26 20_07_12-PerpSim](https://user-images.githubusercontent.com/67635139/214940133-e352f0c2-b45d-4c0b-a9d8-6e4ff4decab8.png)
> 
> ![2023-01-26 20_07_28-PerpSim](https://user-images.githubusercontent.com/67635139/214940165-325b9463-6ac7-4a1e-9995-9d42918e4377.png)
> 
> # Description
> * Added sort functionality for current positions modal table through a table header.
> * Updated styling of modal to reflect new design.
> 
> _**Modal Table Sort Functionality**_ New Component: CurrentPositionsTableSortHeader
> 
> * Moved table header from table to new component.
> * Maps around currentPositionsTableSortByOptionsAtom to create headers
> * Each header contains title, chevron and button which toggles state.
> * Toggle adjusts sort direction and active sort status of header.
> * This changes direction of chevron for header
> * Also changes the sorting of table through modifying currentPositionsTableSortByOptionsAtom which in turn modifies currentPositionsTableSortByOptionsAtom which is called by CurrentPositionsTable.
> 
> New Selector: selectCurrentPositionInformationSorted
> 
> * Takes in currentPositionsTableSortByOptionsAtom which gives sort details for table
> * Takes in changes to currentPositionsTableSortByOptionsAtom from TableHeader button click.
> * Takes in mockData for table.
> * Filters through sort options using the selected option from TableHeader, then uses selected option to output a modified version of mockData by calling appropriate sort functions on it using details from the selected sort option.
> * This sorted data is then rendered by the CurrentPositionsTable
> 
> New Atom: currentPositionsTableSortByOptionsAtom
> 
> * Gives details for each table sort header.
> 
> Modified Component: CurrentPositionsTable
> 
> * Table now maps around selectCurrentPositionInformationSorted, so can interact with the sort functionality enabled by the above.
> * Some style changes to accomodate comma formatting on number values.
> 
> _**Styling**_ Modified Component: CurrentPositionsContainer
> 
> * Amended to add TableSortHeader
> * Styling amended to accomodate updated styling
> 
> Modified Component: CurrentPositionsTable
> 
> * Styling amended to accomodate updated styling and removal of headers to new component.
> 
> Modified Atom: MockDataAtom
> 
> * Amended mock data to replace strings with integers on some values so as to be more realistic.
> 
> ## **Sanity Check**
> * Table should be sorted through toggling the headers on the modal table.
> * Modal should point downwards when value is max-min/A-Z and inversely.
> * Each header should sort according to its title and toggle between ascending and descending values.
> * Table should sort by Market A-Z by default.
> 
> ## **TO DO**
> * [ ]  - selectCurrentPositionInformationSorted which forms basis of table content relies on mockDataAtom, needs to be converted to use real data.

<img width="259" alt="Screenshot 2023-02-03 at 10 06 59 AM" src="https://user-images.githubusercontent.com/18191679/216664421-7f55c2ff-2a69-403f-8038-96aaef190bcd.png">
I noticed that there is some weird styling going on at the bottom with current positions.

2023-02-03 17:09 UTC, Brendan-Lucas approved these changes

2023-02-06 13:04 UTC, merged