Feat/get positions data from contract
Component-fi/perpetual-lp-tool pull request #311
Opened 2023-02-10 19:59 UTC by aindriumorris

## Screenshot
![2023-02-10 19_34_10-PerpSim](https://user-images.githubusercontent.com/67635139/218183415-dd97c91e-78f0-4be0-ae1a-11eaed05b6f1.png)

# Description
- Connected modal with Perpetual sub-graph and contracts 
- Modal now showing users current positions data for asset type, range status, net position, trading fees and impermanent loss

_**Data & Data Queries**_

Modified Selector: selectUserCurrentPositions
- Selector queries for current positions
- Added Querying subgraph for collectedFees
- Getting currentPrice from selectAllPoolsInfo

Modified Selector: selectCurrentPositionsInformation
- Created current positions object mapping around selectUserCurrentPositions subGraph query
- Object ID assigned as position baseTokenAddress-lowerTick-upperTick as this is how positions distinguished in queries from amongst pool data.
- Query Perp orderBook contract for pending fee position data
- Query Perp orderBook contract for token debt data.
- Impermanent Loss calculated using calculateImpermanentLoss, passing in token debt data and some position data from subGraph
- NetPosition calculated using pending+collected fees and impermanent loss data.

Modified Selector: selectCurrentPositionsTableData
- Renamed selectCurrentPositionsTableData instead of selectCurrentPositionInformationSorted to avoid conflicts with selectCurrentPositionsInformation.
- Takes in object from selectCurrentPositionsInformation, convert to array to enable ease of sorting.

_**UI**_
Modified Component: CurrentPositionsTable
- Table now maps around selectCurrentPositionsTableData which is renamed version of selectCurrentPositionInformationSorted which is now selectCurrentPositionsTableData.
- Some style changes to accomodate comma formatting on number values.

Deleted Atom: mockDataAtom
- Gives details for each table sort header.

_**Styling**_
Modified Component: CurrentPositionsTable
- Styling amended to accomodate accomodate impermanent position column, removed rewards column

Modified currentPositionsTableSortByOptionsAtom: 
- Amended table header atom to accomodate impermanent position header, removed rewards header.

## **Sanity Check**

- 
- 

## **TO DO**

- [ ] - Data for position rewards may be possible to add in the future.

2023-02-13 20:00 UTC, Brendan-Lucas requested changes

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                            {position.netPosition! >= 0
this exclamation insists that the netPosition property is not null. Typscript usually complains about this. Does the exclamation mark do something different here? otherwise it should be removed, you can type things with as number.

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/utilities/uniswapConversionUtilities.ts
> +    return 1.0001 ** tick
i know I wrote this code but we need to add a comment or a constant for this 1.0001 
if we use a constant it should still contain the comment "from page five of https://uniswap.org/whitepaper-v3.pdf"

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformation.ts
> +        const orderBookContract = OrderBook__factory.connect(
this should be instantiated outside of the loop, there is no need to do this more than once.

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformation.ts
> +                    positionData.baseTokenDebt!,
these exclamations have the same issue as in the comment I made above.

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformation.ts
> +                    positionData.quoteTokenDebt!,
exclamation same as above

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformation.ts
> +                const inpermanentLoss = calculateImpermanentLoss(
our calculate impermanet loss function is being provided the wrong values here. it wants initial base and quote token amounts. along with present liquidity. I would not necessarily use it here for this purpose given the other information we have access to.

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +            totalFee: positionData.totalFee,
maybe change this to totalFees

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +            rangeStatus: positionData.rangeStatus,
rangeStatus could probably be changed to inRangeStatus or just isInRange is being a keyword for holding a boolean.

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +            netPosition: positionData.netPosition,
net position should be changed to netPositionGain

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
>                      selectedSortOption[0].sortDirection ===
because of the way we are handling this here. I think it makes more sense to just use a key as an argument into the sort function, like ASC/DESC so we don't need the if statement at line 69 instead we pass sort direction directly to `sortNumber(sortDirection)`

2023-02-13 20:00 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
>                      selectedSortOption[0].sortDirection ===
it will save some lines and move that case check out of the main function.

2023-02-14 13:47 UTC, aindriumorris commented on src/recoil/selectors/selectCurrentPositionsInformation.ts
> +        const orderBookContract = OrderBook__factory.connect(
this is not instantiated within a loop?

2023-02-14 15:13 UTC, aindriumorris commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +                            {position.netPosition! >= 0
TS complains if it isn't included.
! are used on the types for the positions which are products of asynchronous queries, therefore their types are number|undefined, by not including !, TS sees this as a possibly undefined error.

2023-02-14 18:58 UTC, Brendan-Lucas requested changes
if you fix these, ill approve right away.

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/components/CurrentPositionsTable/CurrentPositionsTable.tsx
> +/*
we shouldn't add comments to the code either take it out or put it in uncommented. if you want to make a note of something that needs to happen in the future, you can add a TODO

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/containers/SideBarModule/SideBarModule.tsx
> -
this was likely a mistake.

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/recoil/atoms/atoms.ts
> +        /*
Don't add comments, let's take them out or put them back in, or add a TODO indicating that they will be added in the next itteration.

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsInformation.ts
> +        const orderBookContract = OrderBook__factory.connect(
there's a for each at line 31. you can put this at line 27 after we initialize the signer to keep the signer, provider and contract initialization in one place.

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +                    ['desc'],
just double-checking that this wasn't an accident of sortDirection.ASCENDING has orderBy 'desc'

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +                    ['desc'],
Also could you make sortDirection return 'asc' and 'desc' so that you can just pass the sortDirection directly to your orderBy function.

2023-02-14 18:58 UTC, Brendan-Lucas commented on src/utilities/uniswapConversionUtilities.ts
> +    return 1.0001 ** tick //from page five of https://uniswap.org/whitepaper-v3.pd
I think this number is just a little too magic, we really should have it in a constant file.

2023-02-14 19:54 UTC, aindriumorris commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +                    ['desc'],
> just double-checking that this wasn't an accident of sortDirection.ASCENDING has orderBy 'desc'

no, have to do it this way to sort AZ and ZA

2023-02-14 20:03 UTC, aindriumorris commented on src/recoil/selectors/selectCurrentPositionsTableData.ts
> +                    ['desc'],
> Also could you make sortDirection return 'asc' and 'desc' so that you can just pass the sortDirection directly to your orderBy function.

orderBy array for ['desc'] is a boolean, would have to restructure a lot to make that work

2023-02-14 21:55 UTC, Brendan-Lucas approved these changes

2023-02-14 22:48 UTC, merged